[package]
name = "knot"
version = "0.1.0"
edition = "2021"
authors = ["Knot Team"]
description = "A Figma-grade multiplayer desktop environment"

[[bin]]
name = "knot-core"
path = "src/main.rs"

[[bin]]
name = "knot-island"
path = "src/island/main.rs"

[[bin]]
name = "knot-run"
path = "src/launcher/main.rs"

[[bin]]
name = "knot-client"
path = "src/net/client/main.rs"

[dependencies]
smithay = { version = "0.7.0", default-features = false, features = [
    "backend_winit",
    "backend_egl",
    "desktop",
    "wayland_frontend",
    "renderer_glow",
] }
smithay-client-toolkit = { version = "0.19", default-features = false }
wayland-client = "0.31"
wayland-server = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "server"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
glow = "0.16"
tempfile = "3.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = "0.24"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
base64 = "0.22"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
